### ISSUE TITLE
ACNH flower guides conflicting info

### ISSUE THREAD

**Issue by benhead** [aiterusawato/satogu#1]
For Roses, the ACNH Simple Flower Guide says seed yellow 0200 and seed red 2001 produce orange 1101 with 50% chance.
acnh/flowers-simple.html#roses

But the Advanced Flower Guide says 1101 roses are yellow and 1100 roses are orange.
acnh/flowers-advanced.html#genotype-table

BTW love your guides; they've been a huge help - and I'm only doing simple hyacinths so far! Thanks!

**Comment by aiterusawato** [comment]
Now corrected, this orange rose is in fact `1100`.
Thank you for pointing it out !
